@baseUrl = http://localhost:8080

### Register User
POST {{baseUrl}}/register
Content-Type: application/json

{
  "username": "robson",
  "password": "secret"
}

### Login User
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "secret"
}

> {% client.global.set("token", response.body.token) %}

### Post Chat Message
POST {{baseUrl}}/messages
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "Hi, I'm a new student. How do I check my grades?"
}

### Get Last 50 Messages
GET {{baseUrl}}/messages
Authorization: Bearer {{token}}