version: "3.7"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: gochatuser
      POSTGRES_PASSWORD: gochatpass
      POSTGRES_DB: gochatdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro

  app:
    build: .//
    restart: always
    environment:
      DATABASE_URL: postgres://gochatuser:gochatpass@db:5432/gochatdb?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata: